# Generated by Django 5.2.6 on 2026-10-04 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import wardrobe_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(help_text='Upload JPEG or PNG image up to 15MB.', upload_to=wardrobe_app.utils.image_upload_path, validators=[wardrobe_app.utils.validate_image])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'clothing item',
                'verbose_name_plural': 'clothing items',
                'ordering': ['-created_at'],
            },
        ),
    ]
